### ISSUE TITLE
Transform to webservice

### ISSUE THREAD

**Issue by dirrelito** [dirrelito/sprakpolisen-ML-use#2]
The program should be run as a http server with two endpoints. 

# Endpoints 

### Call
GET /check?word=hej
### Returns
    {data: {word: 'hej', prob: 0.123, correct: false}}

### Call
GET /check?words=hej;hopp;allan
### Returns
    {data: [{word: 'hej', prob: 0.123, correct: false},{word: 'hopp', prob: 0.999, correct: false},{word: 'allan', prob: 0.5501, correct: true}]}

### Call
POST /reload?secret=thereisnocake
### HTTP-body input
    {data: {access_key: "asdfasdf"}}
### Returns
    {data: {reload_started: true}}

**Comment by dirrelito** [comment]
What do you think about the contract suggested @marcusahl  ? 
Is the syntax reasonable?
Should we be more future proof? Add better auth? Skip the secret? I dont really like the RPC-feel about the reload-call...
Should the array-call be a POST instead so that the array can be passed as a JSON object?

**Comment by marcusahl** [comment]
I think we shouldnt worry about auth until we need to worry about it :) I for one do not know how to design an auth system, so I dont think we should make half-assed decisions now.

I think the array HTTP body should be {result{data: [{word: "hej",prob: 0.123, correct: "false"}]}} for arrays of length 1 or longer.

**Comment by dirrelito** [comment]
Okay. So o auth = skipping the secret too?

Do you want to only homogenize the return formats, or do you want to scrap the GET-endpoint alltogether?

**Comment by marcusahl** [comment]
I would consolidate to a single GET endpoint.

Lets skip all regarding auth until later, thoughts?

**Comment by dirrelito** [comment]
Sure! Skipping all auth. This is now fixed by PR #3
